[tool.poetry]
name = "web"
version = "0.1.0"
description = ""
authors = ["fumizaki <0238.m.0917@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.40.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
